#  Tamrin Emtiyazi

بردار احتمال مثبت و منفی بودن بازده روزانه سهم بانک ملت را محاسبه کنید

و در ادامه


ماتریس احتمال انتقال مثبت و منفی بودن  بازده روزانه همین سهم را در بازه 2 روز متوالی محاسبه کرده و آن را تحلیل بنمایید


در نهایت آن را در یک دیتافریم پانداز ذخیره کنید

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("dataframe vabemelat.xlsx")

In [9]:
bazdeh = df['Return'].values

In [10]:
bazdeh

array([ 0.00666667, -0.00189215,  0.00473934, ...,  0.03816794,
       -0.00980392,  0.0049505 ])

In [14]:
unigram = np.zeros((2) , int)

for i in range(0 , len(bazdeh)):
    if bazdeh[i] > 0:
        unigram[0] += 1
    if bazdeh[i] < 0:
        unigram[1] += 1
        
# ["ehtemale mosbat budane sahm" , "ehtemale manfi budane sahm"]

In [18]:
unigram = unigram / unigram.sum()

In [19]:
unigram

array([0.48295004, 0.51704996])

In [27]:
Bigram = np.zeros([2,2] , float)

In [28]:
#[[+ --> +    ,   + ----> -],[- ---> +  , - ----> - ]]


for i in range(len(bazdeh) - 1):
    if bazdeh[i] > 0 :
        if bazdeh[i+1] > 0: 
            Bigram[0 , 0] += 1
        if bazdeh[i+1] < 0:
            Bigram[0 , 1] += 1
    if bazdeh[i] < 0:
        if bazdeh[i+1] > 0 :
            Bigram[1 , 0] += 1
        if bazdeh[i+1] < 0 :
            Bigram[1 , 1] += 1


In [29]:
Bigram[0] = Bigram[0] / Bigram.sum(axis = 1)[0]
Bigram[1] = Bigram[1] / Bigram.sum(axis = 1)[1]

In [30]:
Bigram

array([[0.51858108, 0.48141892],
       [0.4826087 , 0.5173913 ]])

In [31]:
pd.DataFrame(columns = ['+'    ,  '-'] , index = ['+'    ,  '-'] , data = Bigram)

+         -
+  0.518581  0.481419
-  0.482609  0.517391